name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rustfmt
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features

  build:
    runs-on: ubuntu-latest
    needs: [style]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        mkdir -p multiproxy-rs
        cargo build --all-targets --all-features --release
        cp target/release/client multiproxy-rs/
        cp target/release/server multiproxy-rs/
        zip -r ubuntu.zip multiproxy-rs
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu
        path: ubuntu.zip

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Read version
        run: echo VERSION=`python3 -c 'import tomllib; f=tomllib.load(open("Cargo.toml","rb")); print(f["package"]["version"])'` >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          name:  ${{ env.VERSION }}
          files: artifacts/**/*.zip
